import Dexie, { type Table } from 'dexie';

// Dexie Cloud removed - using Supabase for sync instead
import { browser } from '$app/environment';

/**
 * Generate a UUID for cloud-synced records
 * Dexie Cloud uses '@id' which should auto-generate, but we need a fallback
 * for offline/unauthenticated scenarios
 */
export function generateId(): string {
    // Use crypto.randomUUID if available (modern browsers)
    if (typeof crypto !== 'undefined' && crypto.randomUUID) {
        return crypto.randomUUID();
    }
    // Fallback for older browsers
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
        const r = Math.random() * 16 | 0;
        const v = c === 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
    });
}
import type { 
    Invoice, Supplier, KnowledgeBaseRule, GlobalContextItem, Product, StockMovement, 
    BankAccount, Payment, Customer, Sale, CashRegisterShift, Return, User, Role, 
    PurchaseOrder, Receipt,
    // Accounting types
    InventoryLot, CostConsumption, JournalEntry, ITBISSummary, CardSettlement,
    // NCF & Audit
    NCFRange, NCFUsage, AccountingAuditEntry,
    // Settings
    ReceiptSettings
} from './types';

// Type for pending sync changes
export interface PendingChangeRecord {
    id?: number;
    tableName: string;
    recordId: string;
    action: 'insert' | 'update' | 'delete';
    data: Record<string, unknown>;
    timestamp: number;
    synced?: boolean;
}
import type { CustomerSegment, TransactionFeatures, RealTimeInsight } from './customer-insights/types';
import type { WeatherRecord } from './weather';
// Note: Dexie Cloud removed - using Supabase for sync instead
// See sync-store.ts and sync-service.ts for sync functionality

// ============ DATABASE CLASS ============

export class MinimarketDatabase extends Dexie {
    // Synced tables (will sync to cloud when enabled)
    invoices!: Table<Invoice>;
    suppliers!: Table<Supplier>;
    rules!: Table<KnowledgeBaseRule>;
    globalContext!: Table<GlobalContextItem>;
    products!: Table<Product>;
    stockMovements!: Table<StockMovement>;
    bankAccounts!: Table<BankAccount>;
    payments!: Table<Payment>;
    customers!: Table<Customer>;
    sales!: Table<Sale>;
    returns!: Table<Return>;
    customerSegments!: Table<CustomerSegment>;
    weatherRecords!: Table<WeatherRecord>;
    purchaseOrders!: Table<PurchaseOrder>;
    receipts!: Table<Receipt>;
    
    // Local-only tables (device-specific data)
    shifts!: Table<CashRegisterShift>;
    users!: Table<User>;
    localRoles!: Table<Role>;
    transactionFeatures!: Table<TransactionFeatures>;
    realTimeInsights!: Table<RealTimeInsight>;
    
    // Accounting tables (FIFO, Journal, ITBIS)
    inventoryLots!: Table<InventoryLot>;
    costConsumptions!: Table<CostConsumption>;
    journalEntries!: Table<JournalEntry>;
    itbisSummaries!: Table<ITBISSummary>;
    cardSettlements!: Table<CardSettlement>;
    ncfRanges!: Table<NCFRange>;
    ncfUsage!: Table<NCFUsage>;
    accountingAuditLog!: Table<AccountingAuditEntry>;
    receiptSettings!: Table<ReceiptSettings>;
    
    // Sync tracking table for Supabase sync
    pendingChanges!: Table<PendingChangeRecord>;

    constructor() {
        // Initialize Dexie database
        // Note: Dexie Cloud removed - using Supabase for sync instead
        // Synced tables use string 'id' for UUIDs (generated by generateId())
        super('Jardines3MinimarketDB');
        
        // ============ SCHEMA DEFINITION ============
        // Version 20: Added NCF and accounting audit tables
        this.version(20).stores({
            // Synced tables - use id for UUID primary keys (we generate UUIDs ourselves)
            invoices: 'id, providerName, issueDate, ncf, status, paymentStatus, dueDate, receiptId, realmId, [issueDate+providerName]',
            suppliers: 'id, name, rnc, isActive, category, realmId',
            rules: 'id, supplierId, realmId',
            globalContext: 'id, title, type, category, realmId',
            products: 'id, supplierId, name, category, barcode, productId, realmId, [supplierId+name]',
            stockMovements: 'id, productId, type, date, invoiceId, receiptId, saleId, returnId, realmId',
            bankAccounts: 'id, bankName, isDefault, isActive, realmId',
            payments: 'id, invoiceId, saleId, returnId, supplierId, customerId, paymentDate, paymentMethod, bankAccountId, realmId',
            customers: 'id, name, type, isActive, rnc, realmId',
            sales: 'id, date, customerId, paymentStatus, shiftId, receiptNumber, cashierId, hasReturns, realmId',
            returns: 'id, date, originalSaleId, originalReceiptNumber, customerId, shiftId, processedBy, refundStatus, realmId',
            customerSegments: 'id, segmentId, segmentName, segmentType, confidenceScore, lastUpdated, realmId',
            weatherRecords: 'id, date, condition, precipitationLevel, location, realmId',
            purchaseOrders: 'id, poNumber, supplierId, status, orderDate, expectedDate, realmId',
            receipts: 'id, receiptNumber, supplierId, purchaseOrderId, receiptDate, invoiceId, realmId',
            
            // Accounting tables - FIFO Inventory
            inventoryLots: 'id, productId, purchaseDate, status, expirationDate, invoiceId, receiptId, realmId, [productId+status]',
            costConsumptions: 'id, saleId, returnId, adjustmentId, lotId, productId, date, realmId',
            
            // Accounting tables - Journal System
            journalEntries: 'id, entryNumber, date, sourceType, sourceId, shiftId, status, realmId, [date+sourceType]',
            
            // Accounting tables - ITBIS Tracking
            itbisSummaries: 'id, period, status, realmId',
            
            // Accounting tables - Card Settlements
            cardSettlements: 'id, settlementDate, status, bankAccountId, journalEntryId, realmId',
            
            // NCF tracking
            ncfRanges: 'id, type, isActive, expirationDate',
            ncfUsage: 'id, ncf, type, saleId, issuedAt, voided',

            // Audit log
            accountingAuditLog: 'id, timestamp, action, entityType, entityId, userId',
            
            // Receipt/Ticket settings
            receiptSettings: 'id',
            
            // Local-only tables ($ prefix removed since Dexie Cloud is gone)
            shifts: '++id, shiftNumber, status, openedAt, closedAt, cashierId',
            users: '++id, username, roleId, isActive, &pin',
            localRoles: '++id, name, isSystem',
            transactionFeatures: '++id, timestamp, hourOfDay, dayOfWeek, totalValue, shiftId',
            realTimeInsights: '++id, insightType, expiresAt, createdAt',
            
            // Sync tracking for Supabase
            pendingChanges: '++id, tableName, recordId, timestamp, synced'
        }).upgrade(async () => {
            console.log('Upgraded to schema v20 - added NCF and accounting audit tables');
        });

        // Version 19: Added accounting tables (FIFO, Journal, ITBIS, Card Settlements)
        // id = UUID string primary key (manually generated)
        // ++id = Auto-increment integer primary key (local-only tables)
        // $ prefix removed from local tables since Dexie Cloud is no longer used
        
        this.version(19).stores({
            // Synced tables - use id for UUID primary keys (we generate UUIDs ourselves)
            invoices: 'id, providerName, issueDate, ncf, status, paymentStatus, dueDate, receiptId, realmId, [issueDate+providerName]',
            suppliers: 'id, name, rnc, isActive, category, realmId',
            rules: 'id, supplierId, realmId',
            globalContext: 'id, title, type, category, realmId',
            products: 'id, supplierId, name, category, barcode, productId, realmId, [supplierId+name]',
            stockMovements: 'id, productId, type, date, invoiceId, receiptId, saleId, returnId, realmId',
            bankAccounts: 'id, bankName, isDefault, isActive, realmId',
            payments: 'id, invoiceId, saleId, returnId, supplierId, customerId, paymentDate, paymentMethod, bankAccountId, realmId',
            customers: 'id, name, type, isActive, rnc, realmId',
            sales: 'id, date, customerId, paymentStatus, shiftId, receiptNumber, cashierId, hasReturns, realmId',
            returns: 'id, date, originalSaleId, originalReceiptNumber, customerId, shiftId, processedBy, refundStatus, realmId',
            customerSegments: 'id, segmentId, segmentName, segmentType, confidenceScore, lastUpdated, realmId',
            weatherRecords: 'id, date, condition, precipitationLevel, location, realmId',
            purchaseOrders: 'id, poNumber, supplierId, status, orderDate, expectedDate, realmId',
            receipts: 'id, receiptNumber, supplierId, purchaseOrderId, receiptDate, invoiceId, realmId',
            
            // Accounting tables - FIFO Inventory
            inventoryLots: 'id, productId, purchaseDate, status, expirationDate, invoiceId, receiptId, realmId, [productId+status]',
            costConsumptions: 'id, saleId, returnId, adjustmentId, lotId, productId, date, realmId',
            
            // Accounting tables - Journal System
            journalEntries: 'id, entryNumber, date, sourceType, sourceId, shiftId, status, realmId, [date+sourceType]',
            
            // Accounting tables - ITBIS Tracking
            itbisSummaries: 'id, period, status, realmId',
            
            // Accounting tables - Card Settlements
            cardSettlements: 'id, settlementDate, status, bankAccountId, journalEntryId, realmId',
            
            // Local-only tables ($ prefix removed since Dexie Cloud is gone)
            shifts: '++id, shiftNumber, status, openedAt, closedAt, cashierId',
            users: '++id, username, roleId, isActive, &pin',
            localRoles: '++id, name, isSystem',
            transactionFeatures: '++id, timestamp, hourOfDay, dayOfWeek, totalValue, shiftId',
            realTimeInsights: '++id, insightType, expiresAt, createdAt',
            
            // Sync tracking for Supabase
            pendingChanges: '++id, tableName, recordId, timestamp, synced'
        }).upgrade(async () => {
            console.log('Upgraded to schema v19 - added accounting tables (FIFO, Journal, ITBIS, Card Settlements)');
        });

        // Version 18: Removed Dexie Cloud, using Supabase for sync
        this.version(18).stores({
            // Synced tables - use id for UUID primary keys (we generate UUIDs ourselves)
            invoices: 'id, providerName, issueDate, ncf, status, paymentStatus, dueDate, receiptId, realmId, [issueDate+providerName]',
            suppliers: 'id, name, rnc, isActive, category, realmId',
            rules: 'id, supplierId, realmId',
            globalContext: 'id, title, type, category, realmId',
            products: 'id, supplierId, name, category, barcode, productId, realmId, [supplierId+name]',
            stockMovements: 'id, productId, type, date, invoiceId, receiptId, saleId, returnId, realmId',
            bankAccounts: 'id, bankName, isDefault, isActive, realmId',
            payments: 'id, invoiceId, saleId, returnId, supplierId, customerId, paymentDate, paymentMethod, bankAccountId, realmId',
            customers: 'id, name, type, isActive, rnc, realmId',
            sales: 'id, date, customerId, paymentStatus, shiftId, receiptNumber, cashierId, hasReturns, realmId',
            returns: 'id, date, originalSaleId, originalReceiptNumber, customerId, shiftId, processedBy, refundStatus, realmId',
            customerSegments: 'id, segmentId, segmentName, segmentType, confidenceScore, lastUpdated, realmId',
            weatherRecords: 'id, date, condition, precipitationLevel, location, realmId',
            purchaseOrders: 'id, poNumber, supplierId, status, orderDate, expectedDate, realmId',
            receipts: 'id, receiptNumber, supplierId, purchaseOrderId, receiptDate, invoiceId, realmId',
            
            // Local-only tables ($ prefix removed since Dexie Cloud is gone)
            shifts: '++id, shiftNumber, status, openedAt, closedAt, cashierId',
            users: '++id, username, roleId, isActive, &pin',
            localRoles: '++id, name, isSystem',
            transactionFeatures: '++id, timestamp, hourOfDay, dayOfWeek, totalValue, shiftId',
            realTimeInsights: '++id, insightType, expiresAt, createdAt',
            
            // Sync tracking for Supabase
            pendingChanges: '++id, tableName, recordId, timestamp, synced'
        });

        // Keep previous versions for backward compatibility
        // Note: v14 adds localRoles migration from roles
        this.version(14).stores({
            invoices: '++id, providerName, issueDate, ncf, status, paymentStatus, dueDate, receiptId, [issueDate+providerName]',
            suppliers: '++id, name, rnc, isActive, category',
            rules: '++id, supplierId',
            globalContext: '++id, title, type, category',
            products: '++id, supplierId, name, category, barcode, productId, [supplierId+name]',
            stockMovements: '++id, productId, type, date, invoiceId, receiptId, saleId, returnId',
            bankAccounts: '++id, bankName, isDefault, isActive',
            payments: '++id, invoiceId, saleId, returnId, supplierId, customerId, paymentDate, paymentMethod, bankAccountId',
            customers: '++id, name, type, isActive, rnc',
            sales: '++id, date, customerId, paymentStatus, shiftId, receiptNumber, cashierId, hasReturns',
            shifts: '++id, shiftNumber, status, openedAt, closedAt, cashierId',
            returns: '++id, date, originalSaleId, originalReceiptNumber, customerId, shiftId, processedBy, refundStatus',
            users: '++id, username, roleId, isActive, &pin',
            localRoles: '++id, name, isSystem', // Renamed from 'roles'
            customerSegments: '++id, segmentId, segmentName, segmentType, confidenceScore, lastUpdated',
            transactionFeatures: '++id, timestamp, hourOfDay, dayOfWeek, totalValue, shiftId',
            realTimeInsights: '++id, insightType, expiresAt, createdAt',
            weatherRecords: '++id, date, condition, precipitationLevel, location',
            purchaseOrders: '++id, poNumber, supplierId, status, orderDate, expectedDate',
            receipts: '++id, receiptNumber, supplierId, purchaseOrderId, receiptDate, invoiceId'
        }).upgrade(async tx => {
            // Migrate data from 'roles' to 'localRoles' if old table exists
            // This handles the rename for existing databases
            console.log('Upgraded to schema v14 with localRoles table');
        });

        // Version 13: Added weather records for weather-based insights
        this.version(13).stores({
            invoices: '++id, providerName, issueDate, ncf, status, paymentStatus, dueDate, [issueDate+providerName]',
            suppliers: '++id, name, rnc, isActive, category',
            rules: '++id, supplierId',
            globalContext: '++id, title, type, category',
            products: '++id, supplierId, name, category, barcode, productId, [supplierId+name]',
            stockMovements: '++id, productId, type, date, invoiceId, saleId, returnId',
            bankAccounts: '++id, bankName, isDefault, isActive',
            payments: '++id, invoiceId, saleId, returnId, supplierId, customerId, paymentDate, paymentMethod, bankAccountId',
            customers: '++id, name, type, isActive, rnc',
            sales: '++id, date, customerId, paymentStatus, shiftId, receiptNumber, cashierId, hasReturns',
            shifts: '++id, shiftNumber, status, openedAt, closedAt, cashierId',
            returns: '++id, date, originalSaleId, originalReceiptNumber, customerId, shiftId, processedBy, refundStatus',
            users: '++id, username, roleId, isActive, &pin',
            localRoles: '++id, name, isSystem',
            customerSegments: '++id, segmentId, segmentName, segmentType, confidenceScore, lastUpdated',
            transactionFeatures: '++id, timestamp, hourOfDay, dayOfWeek, totalValue, shiftId',
            realTimeInsights: '++id, insightType, expiresAt, createdAt',
            weatherRecords: '++id, date, condition, precipitationLevel, location'
        });
        
        // Version 12: Added customer insights tables for AI-powered analytics
        this.version(12).stores({
            invoices: '++id, providerName, issueDate, ncf, status, paymentStatus, dueDate, [issueDate+providerName]',
            suppliers: '++id, name, rnc, isActive, category',
            rules: '++id, supplierId',
            globalContext: '++id, title, type, category',
            products: '++id, supplierId, name, category, barcode, productId, [supplierId+name]',
            stockMovements: '++id, productId, type, date, invoiceId, saleId, returnId',
            bankAccounts: '++id, bankName, isDefault, isActive',
            payments: '++id, invoiceId, saleId, returnId, supplierId, customerId, paymentDate, paymentMethod, bankAccountId',
            customers: '++id, name, type, isActive, rnc',
            sales: '++id, date, customerId, paymentStatus, shiftId, receiptNumber, cashierId, hasReturns',
            shifts: '++id, shiftNumber, status, openedAt, closedAt, cashierId',
            returns: '++id, date, originalSaleId, originalReceiptNumber, customerId, shiftId, processedBy, refundStatus',
            users: '++id, username, roleId, isActive, &pin',
            localRoles: '++id, name, isSystem',
            customerSegments: '++id, segmentId, segmentName, segmentType, confidenceScore, lastUpdated',
            transactionFeatures: '++id, timestamp, hourOfDay, dayOfWeek, totalValue, shiftId',
            realTimeInsights: '++id, insightType, expiresAt, createdAt'
        });
        
        // Version 11: Added returns, users, and roles for multi-user POS with returns capability
        this.version(11).stores({
            invoices: '++id, providerName, issueDate, ncf, status, paymentStatus, dueDate, [issueDate+providerName]',
            suppliers: '++id, name, rnc, isActive, category',
            rules: '++id, supplierId',
            globalContext: '++id, title, type, category',
            products: '++id, supplierId, name, category, barcode, productId, [supplierId+name]',
            stockMovements: '++id, productId, type, date, invoiceId, saleId, returnId',
            bankAccounts: '++id, bankName, isDefault, isActive',
            payments: '++id, invoiceId, saleId, returnId, supplierId, customerId, paymentDate, paymentMethod, bankAccountId',
            customers: '++id, name, type, isActive, rnc',
            sales: '++id, date, customerId, paymentStatus, shiftId, receiptNumber, cashierId, hasReturns',
            shifts: '++id, shiftNumber, status, openedAt, closedAt, cashierId',
            returns: '++id, date, originalSaleId, originalReceiptNumber, customerId, shiftId, processedBy, refundStatus',
            users: '++id, username, roleId, isActive, &pin',
            localRoles: '++id, name, isSystem'
        });
        
        // Version 10: Added cash register shifts for turn management (cortes de caja)
        this.version(10).stores({
            invoices: '++id, providerName, issueDate, ncf, status, paymentStatus, dueDate, [issueDate+providerName]',
            suppliers: '++id, name, rnc, isActive, category',
            rules: '++id, supplierId',
            globalContext: '++id, title, type, category',
            products: '++id, supplierId, name, category, barcode, productId, [supplierId+name]',
            stockMovements: '++id, productId, type, date, invoiceId, saleId',
            bankAccounts: '++id, bankName, isDefault, isActive',
            payments: '++id, invoiceId, saleId, supplierId, customerId, paymentDate, paymentMethod, bankAccountId',
            customers: '++id, name, type, isActive, rnc',
            sales: '++id, date, customerId, paymentStatus, shiftId, receiptNumber',
            shifts: '++id, shiftNumber, status, openedAt, closedAt'
        });
    }
    
    // Initialize default roles and admin user if needed
    async initializeDefaults() {
        const rolesCount = await this.localRoles.count();
        if (rolesCount === 0) {
            // Import DEFAULT_ROLES dynamically to avoid circular dependency
            const { DEFAULT_ROLES } = await import('./types');
            
            // Add default roles
            for (const role of DEFAULT_ROLES) {
                await this.localRoles.add({
                    ...role,
                    createdAt: new Date()
                });
            }
            
            // Create default admin user with PIN 2024
            const adminRole = await this.localRoles.where('name').equals('Administrador').first();
            if (adminRole?.id) {
                await this.users.add({
                    username: 'admin',
                    displayName: 'Administrador',
                    pin: '2024',
                    roleId: adminRole.id,
                    roleName: adminRole.name,
                    isActive: true,
                    createdAt: new Date()
                });
            }
        }
    }
}

// ============ DATABASE INSTANCE ============

// Check if IndexedDB is available (Safari private browsing may block it)
function isIndexedDBAvailable(): boolean {
    if (!browser) return false;
    try {
        // Quick test to see if indexedDB is accessible
        const testRequest = indexedDB.open('__test__');
        testRequest.onerror = () => {};
        testRequest.onsuccess = () => {
            testRequest.result.close();
            indexedDB.deleteDatabase('__test__');
        };
        return true;
    } catch (e) {
        console.warn('IndexedDB not available (Safari private browsing?):', e);
        return false;
    }
}

// Only create the database instance in the browser if IndexedDB is available
let dbInstance: MinimarketDatabase | null = null;
if (browser) {
    try {
        if (isIndexedDBAvailable()) {
            dbInstance = new MinimarketDatabase();
        } else {
            console.warn('IndexedDB blocked - running in limited mode without local persistence');
        }
    } catch (e) {
        console.error('Failed to create database instance:', e);
    }
}

export const db = dbInstance ?? (null as unknown as MinimarketDatabase);

// ============ SYNC CONFIGURATION (SUPABASE) ============
// Dexie Cloud has been removed - using Supabase for sync instead
// See sync-service.ts and device-auth.ts for sync functionality

// ============ DATABASE INITIALIZATION ============

// Safe localStorage helpers for Safari compatibility
function safeLocalStorageGet(key: string): string | null {
    if (!browser) return null;
    try {
        return localStorage.getItem(key);
    } catch (error) {
        console.warn('localStorage.getItem failed (Safari private browsing?):', error);
        return null;
    }
}

function safeLocalStorageSet(key: string, value: string): void {
    if (!browser) return;
    try {
        localStorage.setItem(key, value);
    } catch (error) {
        console.warn('localStorage.setItem failed (Safari private browsing?):', error);
    }
}

function safeLocalStorageRemove(key: string): void {
    if (!browser) return;
    try {
        localStorage.removeItem(key);
    } catch (error) {
        console.warn('localStorage.removeItem failed:', error);
    }
}

// Promise that resolves when database is fully ready (including defaults initialized)
let dbReadyResolve: () => void;
let dbReadyReject: (err: Error) => void;
let dbReadyResolved = false;

export const dbReady: Promise<void> = browser 
    ? new Promise((resolve, reject) => {
        dbReadyResolve = () => {
            if (!dbReadyResolved) {
                dbReadyResolved = true;
                resolve();
            }
        };
        dbReadyReject = (err: Error) => {
            if (!dbReadyResolved) {
                dbReadyResolved = true;
                reject(err);
            }
        };
    })
    : Promise.resolve();

// Ensure database is open and ready (only in browser)
if (browser && db) {
    // Add a timeout to prevent infinite loading (Safari safety net)
    // Reduced to 8 seconds for better UX
    const dbTimeout = setTimeout(() => {
        console.warn('Database initialization timeout - resolving anyway to prevent infinite loading');
        dbReadyResolve();
    }, 8000); // 8 second timeout
    
    // Open database (Supabase sync is handled separately in sync-service.ts)
    db.open()
        .then(() => {
            // Initialize default roles and admin user
            return db.initializeDefaults();
        })
        .then(() => {
            clearTimeout(dbTimeout);
            console.log('Database initialized successfully with defaults');
            dbReadyResolve();
        })
        .catch(async (err) => {
            clearTimeout(dbTimeout);
            
            // Log detailed error information - convert error to JSON if possible
            let errorMsg = '';
            try {
                errorMsg = JSON.stringify(err, Object.getOwnPropertyNames(err));
            } catch {
                errorMsg = String(err?.message || err);
            }
            console.error('Failed to open database:', errorMsg);
            
            // Check if we've already tried resetting to prevent infinite loop
            const resetAttemptKey = 'dexie_cloud_reset_attempt';
            const lastResetAttempt = safeLocalStorageGet(resetAttemptKey);
            const now = Date.now();
            const hasRecentResetAttempt = lastResetAttempt && (now - parseInt(lastResetAttempt, 10)) < 10000; // 10 seconds
            
            // For Dexie Cloud, schema mismatches often require a fresh start
            const errorStr = String(err?.message || err);
            const needsReset = 
                !hasRecentResetAttempt && (
                    err?.name === 'VersionError' || 
                    err?.name === 'UpgradeError' ||
                    err?.name === 'InvalidStateError' ||
                    errorStr.includes('schema') ||
                    errorStr.includes('version') ||
                    errorStr.includes('upgrade')
                );
            
            if (needsReset) {
                console.warn('Database error detected - resetting database for Dexie Cloud compatibility...');
                console.warn('Your local data will be cleared. If you have cloud sync enabled, data will be restored from cloud.');
                try {
                    safeLocalStorageSet(resetAttemptKey, String(now));
                    await Dexie.delete('Jardines3MinimarketDB');
                    window.location.reload();
                } catch (deleteErr) {
                    console.error('Failed to delete database:', deleteErr);
                    dbReadyResolve(); // Resolve anyway to prevent infinite loading
                }
            } else {
                // Clear reset attempt flag on non-reset errors
                if (hasRecentResetAttempt) {
                    console.error('Database reset did not resolve the issue. Error:', errorMsg);
                    safeLocalStorageRemove(resetAttemptKey);
                }
                // Try to continue without cloud sync by resolving anyway
                console.warn('Continuing without full cloud sync functionality...');
                dbReadyResolve();
            }
        });
}

// ============ UTILITY FUNCTIONS ============
// Note: Cloud-related utilities (isCloudSyncAvailable, getCloudUser) removed
// Use device-auth.ts for device registration status instead
